AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  nested-stack-storage

  Root stack to showcase nested stack resources

Parameters:
  StackName:
    Type: String
    Description: The name of the main stack

Resources:

  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:  !Sub "${StackName}-nested-stack"


  # SecondStorageBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName:  !Sub ${AWS::StackName}-second-nested-stack
Outputs:

  S3BucketName:
    Description: "S3 Bucket Name for game data"
    Value: !Ref StorageBucket
